### ISSUE TITLE
Le logo du site est créé

### ISSUE THREAD

**Issue by liZe** [Kozea/pyconfr_2017#1]

**Comment by annabellou** [comment]
Voici !
https://drive.google.com/open?id=0B62Ll0D3yTZ6Q29tTncwVlY0UWc

**Comment by annabellou** [comment]
![logo pycon 2017](https://cloud.githubusercontent.com/assets/7512422/26404784/68c21e7c-4093-11e7-94a9-fd07385c36a0.png)

https://drive.google.com/open?id=0B62Ll0D3yTZ6X2FRY2pDSS1QTGc
