### ISSUE TITLE
Le style du site est intégré

### ISSUE THREAD

**Issue by liZe** [Kozea/pyconfr_2017#2]

**Comment by annabellou** [comment]
Maquette de la page d'accueil
https://drive.google.com/open?id=0B62Ll0D3yTZ6eGNtYVU5V0hWNms

**Comment by annabellou** [comment]
Une pull request a été faite ce jour !

**Comment by annabellou** [comment]
Le style a été mis en ligne !
https://www.pycon.fr/2017/
